#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

---
resources:
# apachegeode-build-concourse resources
- name: apachegeode-build-concourse-dockerfile
  type: git
  source:
    uri: https://github.com/((!geode-fork))/geode.git
    branch: ((!geode-build-branch))
    paths:
    - ci/docker/*

- name: apachegeode-build-concourse-docker-image
  type: docker-image
  source:
    username: ((!docker-username))
    password: ((!docker-password))
    repository: gcr.io/apachegeode-ci/((!docker-image-prefix))((!docker-image-name))

- name: openjdk8-docker-image
  type: docker-image
  source:
    repository: openjdk
    tag: 8

- name: google-geode-builder
  type: git
  source:
    uri: https://github.com/((!geode-fork))/geode.git
    branch: ((!geode-build-branch))
    paths:
    - ci/images/google-geode-builder

- name: alpine37-docker-image
  type: docker-image
  source:
    repository: alpine
    tag: 3.7
    skip_download: true

- name: alpine-docker-image
  type: docker-image
  source:
    repository: alpine
    tag: latest
    skip_download: true

- name: alpine-tools-dockerfile
  type: git
  source:
    uri: https://github.com/((!geode-fork))/geode.git
    branch: ((!geode-build-branch))
    paths:
    - ci/images/alpine-tools/*

- name: alpine-tools-docker-image
  type: docker-image
  source:
    username: ((!docker-username))
    password: ((!docker-password))
    repository: gcr.io/apachegeode-ci/((!docker-image-prefix))alpine-tools

- name: concourse-metadata-resource-dockerfile
  type: git
  source:
    uri: https://github.com/((!geode-fork))/geode.git
    branch: ((!geode-build-branch))
    paths:
    - ci/images/concourse-metadata-resource/*

- name: concourse-metadata-resource-docker-image
  type: docker-image
  source:
    username: ((!docker-username))
    password: ((!docker-password))
    repository: gcr.io/apachegeode-ci/((!docker-image-prefix))concourse-metadata-resource

jobs:
# apachegeode-build-concourse
- name: build-apachegeode-build-concourse-docker-image
  public: ((!public-pipelines))
  serial: true
  plan:
  - aggregate:
    - get: openjdk8-docker-image
      trigger: true
    - get: apachegeode-build-concourse-dockerfile
      trigger: true
  - put: apachegeode-build-concourse-docker-image
    params:
      build: apachegeode-build-concourse-dockerfile/ci/docker
      tag_as_latest: true

- name: build-google-geode-builder
  public: ((!public-pipelines))
  serial: true
  plan:
  - aggregate:
    - get: apachegeode-build-concourse-docker-image
      passed: [build-apachegeode-build-concourse-docker-image]
      trigger: true
    - get: google-geode-builder
      trigger: true
    - get: alpine-tools-docker-image
  - task: build-image
    image: alpine-tools-docker-image
    config:
      inputs:
      - name: google-geode-builder
      outputs:
      - name: results
      platform: linux
      params:
        GEODE_FORK: ((!geode-fork))
        GEODE_BRANCH: ((!geode-build-branch))
        GEODE_DOCKER_IMAGE: gcr.io/apachegeode-ci/((!docker-image-prefix))((!docker-image-name))
      run:
        path: google-geode-builder/ci/images/google-geode-builder/build_image.sh

- name: build-alpine-tools-docker-image
  public: ((!public-pipelines))
  serial: true
  plan:
  - aggregate:
    - get: alpine37-docker-image
      trigger: true
    - get: alpine-tools-dockerfile
      trigger: true
  - put: alpine-tools-docker-image
    params:
      build: alpine-tools-dockerfile/ci/images/alpine-tools
      tag_as_latest: true

- name: build-concourse-metadata-resource-docker-image
  public: ((!public-pipelines))
  serial: true
  plan:
  - aggregate:
    - get: alpine-docker-image
      trigger: true
    - get: concourse-metadata-resource-dockerfile
      trigger: true
  - put: concourse-metadata-resource-docker-image
    params:
      build: concourse-metadata-resource-dockerfile/ci/images/concourse-metadata-resource
      tag_as_latest: true
