/*
 * Licensed to the Apache Software Foundation (ASF) under one or more contributor license
 * agreements. See the NOTICE file distributed with this work for additional information regarding
 * copyright ownership. The ASF licenses this file to You under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance with the License. You may obtain a
 * copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
package org.apache.geode.metrics;

/**
 * Publishes metrics generated by meters in the cache meter registry.
 */
public interface MetricsPublishingService {

  /**
   * Invoked when a metrics session is started during cache initialization. The implementation can
   * use the cache metrics session to connect downstream registries to the cache meter registry for
   * publishing metrics to external monitoring systems.
   *
   * @param session the cache metrics session that is used to connect downstream registries
   */
  void start(MetricsSession session);

  /**
   * Invoked when a metrics session is stopped during cache close.
   */
  void stop();
}
