#!/bin/bash
#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

set -x
set -e

BUILD_DIR=$1
REQUEST=$(cat <&0)

echo "BUILD_DIR: ${BUILD_DIR}" >&2
echo "REQUEST: ${REQUEST}" >&2

filter=$(echo "${REQUEST}" | jq -r '.source.filter // empty')

instances=$(gcloud compute instances list \
              --filter="$(eval echo \"${filter}\")" \
              --format='json(id)')

VERSIONS="${instances}"

if [ -z "${VERSIONS}" ]; then
  RESPONSE='[]'
else
  RESPONSE="${VERSIONS}"
fi

echo "RESPONSE ${RESPONSE}" >&2
echo "${RESPONSE}"

exit 0
