# This is invoked from ANT with many 
# variables defined on the command line.

default: all

LIBRARY = querytests

XTRA_LIB_PATHS =
XTRA_LIBS = -ltestobject -lpdxobject
XTRA_INCS =

include $(BASEDIR)/makefiles/test_library.gmk
