// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//    https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

def doTest(env, target = "test") {
  sh """
  java -version
  ./gradlew ${target}
  """
}

pipeline {
  agent none
  stages {
    stage('Unit Tests') {
      parallel {
        stage('Unit Tests - Java 8') {
          agent { label 'ubuntu' }
          tools {
                jdk 'jdk_1.8_latest'
          }
          steps {
            doTest(env, ":geode-unsafe:test")
          }
        }
        stage('Unit Tests - Java 11') {
          agent { label 'ubuntu' }
          tools {
            jdk 'jdk_11_latest'
          }
          steps {
            doTest(env)
          }
        }
        stage('Unit Tests - Java 17') {
          agent { label 'ubuntu' }
          tools {
            jdk 'jdk_17_latest'
          }
          steps {
            doTest(env)
          }
        }
      }
    }
  }
}