# This is invoked from ANT with many 
# variables defined on the command line.

default: all

SUITE = tools

CPP_OPTIONS = -I$(BASEDIR)/tests/fwklib

BUILD_EXES = checkTS

include $(BASEDIR)/makefiles/test_executables.gmk
