if (DEFINED ENV{GFCPP})
    MESSAGE(STATUS "Using GFCPP=$ENV{GFCPP} as product directory.")
    set( NCProductDir $ENV{GFCPP} )
else()
    if (WIN32)
        file( GLOB NCCandidates /pivotal-gemfire-nativeclient* )
        #peek registry https://cmake.org/Wiki/CMake_FAQ#How%5Fcan%5FI%5Fget%5Fa%5Fwindows%5Fregistry%5Fkey%5F.3F
    else()
        file( GLOB NCCandidates /pivotal-gemfire-nativeclient* )
        if (NOT NCCandidates)
            file( GLOB NCCandidates /gemfire-nativeclient* )
            if (NOT NCCandidates)
                file( GLOB NCCandidates /usr/local/gemfire-nativeclient* )
                if (NOT NCCandidates)
                    file( GLOB NCCandidates /Applications/Pivotal_GemFire_NativeClient* )
                endif()
            endif()
        endif()
    endif()

    if (NCCandidates)
        list(SORT NCCandidates)
        list(REVERSE NCCandidates)
        list(GET NCCandidates 0 NCProductDir)
        MESSAGE(STATUS "Derived ${NCProductDir} as product directory.")
    else()
        MESSAGE(FATAL_ERROR "GFCPP is not set and could not be derived!")
    endif()
endif()

# run gfcpp.exe and make sure we get a version back

#set( NATIVECLIENT_VERSION_STRING "9.0" )
#set( NATIVECLIENT_FOUND "YES" )
set( NATIVECLIENT_DIR ${NCProductDir} )
set( NATIVECLIENT_INCLUDE_DIR ${NCProductDir}/include )
set( NATIVECLIENT_LIBRARIES ${NCProductDir}/lib )
set( NATIVECLIENT_BINARIES_DIR ${NCProductDir}/bin )
