# This is invoked from ANT with many 
# variables defined on the command line.

default: all

LIBRARY = utils
CPP_OPTIONS =

XTRA_LIB_PATHS =
XTRA_LIBS = -lsecurity
XTRA_INCS =

include $(BASEDIR)/makefiles/test_library.gmk
