# This is invoked from ANT with many 
# variables defined on the command line.

default: all

LIBRARY = testobject
CPP_OPTIONS = -DBUILD_TESTOBJECT

XTRA_LIB_PATHS =
XTRA_LIBS =
XTRA_INCS =

include $(BASEDIR)/makefiles/test_library.gmk
