/*
 * Licensed to the Apache Software Foundation (ASF) under one or more contributor license
 * agreements. See the NOTICE file distributed with this work for additional information regarding
 * copyright ownership. The ASF licenses this file to You under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance with the License. You may obtain a
 * copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
package org.apache.geode.cache.control;

import java.util.Map;

import org.apache.geode.cache.partition.PartitionRebalanceInfo;
import org.apache.geode.internal.cache.control.RestoreRedundancyRegionResult;
import org.apache.geode.internal.cache.partitioned.PartitionedRegionRebalanceOp;

/**
 * A class to collect the results of restore redundancy operations for one or more regions and
 * determine the success of failure of the operation.
 */
public interface RestoreRedundancyResults {

  /**
   * {@link #SUCCESS} is defined as every included region having at least one redundant copy.
   * {@link #FAILURE} is defined as at least one region that is configured to have redundant copies
   * having zero redundant copies.
   * {@link #ERROR} is for cases when the restore redundancy operation was unable to begin or threw
   * an exception.
   */
  enum Status {
    SUCCESS,
    FAILURE,
    ERROR
  }

  /**
   * Adds the contents of another {@link RestoreRedundancyResults} object to this one, including
   * both {@link RestoreRedundancyRegionResult} objects and information on the number of primaries
   * reassigned and the time taken to reassign them.
   *
   * @param results a {@link RestoreRedundancyResults} object whose contents will be added to this
   *        one.
   */
  void addRegionResults(RestoreRedundancyResults results);

  /**
   * Adds information regarding the number of primaries reassigned and the time taken to reassign
   * them during a restore redundancy operation.
   *
   * @param details a {@link PartitionRebalanceInfo} generated by a
   *        {@link PartitionedRegionRebalanceOp} operation.
   */
  void addPrimaryReassignmentDetails(PartitionRebalanceInfo details);

  /**
   * Adds one {@link RestoreRedundancyRegionResult} to the result set.
   *
   * @param regionResult The {@link RestoreRedundancyRegionResult} to be added to the result set.
   */
  void addRegionResult(RestoreRedundancyRegionResult regionResult);

  /**
   * Returns the {@link Status} of this restore redundancy operation. Possible statuses are
   * {@link Status#SUCCESS}, {@link Status#FAILURE} and {@link Status#ERROR}.
   *
   * @return The {@link Status} of this restore redundancy operation.
   */
  Status getStatus();

  /**
   * Returns a message describing the results of this restore redundancy operation.
   *
   * @return A {@link String} describing the results of this restore redundancy operation.
   */
  String getMessage();

  /**
   * Returns the {@link RestoreRedundancyRegionResult} for a specific region or null if that region
   * is not present in this {@link RestoreRedundancyResults}.
   *
   * @param regionName The region to which the {@link RestoreRedundancyRegionResult} to be returned
   *        belongs.
   * @return A {@link RestoreRedundancyRegionResult} for the specified region or null if that region
   *         is not present in this {@link RestoreRedundancyResults}.
   */
  RestoreRedundancyRegionResult getRegionResult(String regionName);

  /**
   * Returns all the {@link RestoreRedundancyRegionResult RestoreRedundancyRegionResults} for
   * regions with configured redundancy but zero actual redundant copies.
   *
   * @return A {@link Map} of {@link String} region name to {@link RestoreRedundancyRegionResult}
   *         for every region contained in this {@link RestoreRedundancyResults} with configured
   *         redundancy but zero actual redundant copies.
   */
  Map<String, RestoreRedundancyRegionResult> getZeroRedundancyRegionResults();

  /**
   * Returns all the {@link RestoreRedundancyRegionResult RestoreRedundancyRegionResults} for
   * regions with with at least one redundant copy, but fewer than the configured number of
   * redundant copies.
   *
   * @return A {@link Map} of {@link String} region name to {@link RestoreRedundancyRegionResult}
   *         for every region contained in this {@link RestoreRedundancyResults} with at least one
   *         redundant copy, but fewer than the configured number of redundant copies.
   */
  Map<String, RestoreRedundancyRegionResult> getUnderRedundancyRegionResults();

  /**
   * Returns all the {@link RestoreRedundancyRegionResult RestoreRedundancyRegionResults} for
   * regions with redundancy satisfied.
   *
   * @return A {@link Map} of {@link String} region name to {@link RestoreRedundancyRegionResult}
   *         for every region contained in this {@link RestoreRedundancyResults} with redundancy
   *         satisfied.
   */
  Map<String, RestoreRedundancyRegionResult> getSatisfiedRedundancyRegionResults();

  /**
   * Returns all the {@link RestoreRedundancyRegionResult RestoreRedundancyRegionResults} contained
   * in this {@link RestoreRedundancyResults}. This method may return the actual backing map
   * depending on implementation.
   *
   * @return A {@link Map} of {@link String} region name to {@link RestoreRedundancyRegionResult}
   *         for every region contained in this {@link RestoreRedundancyResults}.
   */
  Map<String, RestoreRedundancyRegionResult> getRegionResults();

  /**
   * Returns the total number of primaries that were transferred as part of the
   * restore redundancy operations.
   *
   * @return the total number of primaries that were transferred
   */
  int getTotalPrimaryTransfersCompleted();

  /**
   * Returns the total time, in milliseconds, spent transferring primaries as part of the
   * restore redundancy operations.
   *
   * @return the total time, in milliseconds, spent transferring primaries
   */
  long getTotalPrimaryTransferTime();

}
