#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
---
image_resource: &docker-geode-build-image
  type: docker-image
  source:
    username: ((!docker-username))
    password: ((!docker-password))
    repository: gcr.io/((gcp-project))/metric-tools
    tag: latest

resources:
- name: once-a-day
  type: time
  source:
    interval: 24h
- name: geode-ci
  type: git
  source:
    depth: 1
    uri: https://github.com/apache/geode.git
    branch: develop
    paths:
    - ci/*

jobs:
- name: GeodeBuildMetrics
  serial: true
  public: true
  plan:
  - get: geode-ci
  - get: once-a-day
    trigger: true
  - task: get_metrics
    config:
      inputs:
      - name: geode-ci
      outputs:
      - name: workspace
      platform: linux
      image_resource: *docker-geode-build-image
      run:
        path: /usr/bin/python3
        args:
        - geode-ci/ci/bin/concourse_job_performance.py
        - ((concourse-url))
        - develop
        - Build
        - 50

- name: GeodeUnitTestOpenJDK8Metrics
  serial: true
  public: true
  plan:
  - get: geode-ci
  - get: once-a-day
    trigger: true
  - task: get_metrics
    config:
      inputs:
      - name: geode-ci
      outputs:
      - name: workspace
      platform: linux
      image_resource: *docker-geode-build-image
      run:
        path: /usr/bin/python3
        args:
        - geode-ci/ci/bin/concourse_job_performance.py
        - https://concourse.apachegeode-ci.info
        - develop
        - UnitTestOpenJDK8
        - 50

- name: GeodeUnitTestOpenJDK11Metrics
  serial: true
  public: true
  plan:
  - get: geode-ci
  - get: once-a-day
    trigger: true
  - task: get_metrics
    config:
      inputs:
      - name: geode-ci
      outputs:
      - name: workspace
      platform: linux
      image_resource: *docker-geode-build-image
      run:
        path: /usr/bin/python3
        args:
        - geode-ci/ci/bin/concourse_job_performance.py
        - ((concourse-url))
        - develop
        - UnitTestOpenJDK11
        - 50

- name: GeodeAcceptanceTestOpenJDK8Metrics
  serial: true
  public: true
  plan:
  - get: geode-ci
  - get: once-a-day
    trigger: true
  - task: get_metrics
    config:
      inputs:
      - name: geode-ci
      outputs:
      - name: workspace
      platform: linux
      image_resource: *docker-geode-build-image
      run:
        path: /usr/bin/python3
        args:
        - geode-ci/ci/bin/concourse_job_performance.py
        - ((concourse-url))
        - develop
        - AcceptanceTestOpenJDK8
        - 50

- name: GeodeAcceptanceTestOpenJDK11Metrics
  serial: true
  public: true
  plan:
  - get: geode-ci
  - get: once-a-day
    trigger: true
  - task: get_metrics
    config:
      inputs:
      - name: geode-ci
      outputs:
      - name: workspace
      platform: linux
      image_resource: *docker-geode-build-image
      run:
        path: /usr/bin/python3
        args:
        - geode-ci/ci/bin/concourse_job_performance.py
        - https://concourse.apachegeode-ci.info
        - develop
        - AcceptanceTestOpenJDK11
        - 50

- name: GeodeDistributedTestOpenJDK8Metrics
  serial: true
  public: true
  plan:
  - get: geode-ci
  - get: once-a-day
    trigger: true
  - task: get_metrics
    config:
      inputs:
      - name: geode-ci
      outputs:
      - name: workspace
      platform: linux
      image_resource: *docker-geode-build-image
      run:
        path: /usr/bin/python3
        args:
        - geode-ci/ci/bin/concourse_job_performance.py
        - ((concourse-url))
        - develop
        - DistributedTestOpenJDK8
        - 50

- name: GeodeDistributedTestOpenJDK11Metrics
  serial: true
  public: true
  plan:
  - get: geode-ci
  - get: once-a-day
    trigger: true
  - task: get_metrics
    config:
      inputs:
      - name: geode-ci
      outputs:
      - name: workspace
      platform: linux
      image_resource: *docker-geode-build-image
      run:
        path: /usr/bin/python3
        args:
        - geode-ci/ci/bin/concourse_job_performance.py
        - https://concourse.apachegeode-ci.info
        - develop
        - DistributedTestOpenJDK11
        - 50

- name: GeodeIntegrationTestOpenJDK8Metrics
  serial: true
  public: true
  plan:
  - get: geode-ci
  - get: once-a-day
    trigger: true
  - task: get_metrics
    config:
      inputs:
      - name: geode-ci
      outputs:
      - name: workspace
      platform: linux
      image_resource: *docker-geode-build-image
      run:
        path: /usr/bin/python3
        args:
        - geode-ci/ci/bin/concourse_job_performance.py
        - https://concourse.apachegeode-ci.info
        - develop
        - IntegrationTestOpenJDK8
        - 50

- name: GeodeIntegrationTestOpenJDK11Metrics
  serial: true
  public: true
  plan:
  - get: geode-ci
  - get: once-a-day
    trigger: true
  - task: get_metrics
    config:
      inputs:
      - name: geode-ci
      outputs:
      - name: workspace
      platform: linux
      image_resource: *docker-geode-build-image
      run:
        path: /usr/bin/python3
        args:
        - geode-ci/ci/bin/concourse_job_performance.py
        - https://concourse.apachegeode-ci.info
        - develop
        - IntegrationTestOpenJDK11
        - 50

- name: GeodeUpgradeTestOpenJDK8Metrics
  serial: true
  public: true
  plan:
  - get: geode-ci
  - get: once-a-day
    trigger: true
  - task: get_metrics
    config:
      inputs:
      - name: geode-ci
      outputs:
      - name: workspace
      platform: linux
      image_resource: *docker-geode-build-image
      run:
        path: /usr/bin/python3
        args:
        - geode-ci/ci/bin/concourse_job_performance.py
        - https://concourse.apachegeode-ci.info
        - develop
        - UpgradeTestOpenJDK8
        - 50

- name: GeodeUpgradeTestOpenJDK11Metrics
  serial: true
  public: true
  plan:
  - get: geode-ci
  - get: once-a-day
    trigger: true
  - task: get_metrics
    config:
      inputs:
      - name: geode-ci
      outputs:
      - name: workspace
      platform: linux
      image_resource: *docker-geode-build-image
      run:
        path: /usr/bin/python3
        args:
        - geode-ci/ci/bin/concourse_job_performance.py
        - https://concourse.apachegeode-ci.info
        - develop
        - UpgradeTestOpenJDK11
        - 50

- name: GeodeWindowsAcceptanceTestOpenJDK8Metrics
  serial: true
  public: true
  plan:
  - get: geode-ci
  - get: once-a-day
    trigger: true
  - task: get_metrics
    config:
      inputs:
      - name: geode-ci
      outputs:
      - name: workspace
      platform: linux
      image_resource: *docker-geode-build-image
      run:
        path: /usr/bin/python3
        args:
        - geode-ci/ci/bin/concourse_job_performance.py
        - https://concourse.apachegeode-ci.info
        - develop
        - WindowsAcceptanceTestOpenJDK8
        - 50

- name: GeodeWindowsAcceptanceTestOpenJDK11Metrics
  serial: true
  public: true
  plan:
  - get: geode-ci
  - get: once-a-day
    trigger: true
  - task: get_metrics
    config:
      inputs:
      - name: geode-ci
      outputs:
      - name: workspace
      platform: linux
      image_resource: *docker-geode-build-image
      run:
        path: /usr/bin/python3
        args:
        - geode-ci/ci/bin/concourse_job_performance.py
        - https://concourse.apachegeode-ci.info
        - develop
        - WindowsAcceptanceTestOpenJDK11
        - 50

- name: GeodeWindowsGfshDistributedTestOpenJDK8Metrics
  serial: true
  public: true
  plan:
  - get: geode-ci
  - get: once-a-day
    trigger: true
  - task: get_metrics
    config:
      inputs:
      - name: geode-ci
      outputs:
      - name: workspace
      platform: linux
      image_resource: *docker-geode-build-image
      run:
        path: /usr/bin/python3
        args:
        - geode-ci/ci/bin/concourse_job_performance.py
        - https://concourse.apachegeode-ci.info
        - develop
        - WindowsGfshDistributedTestOpenJDK8
        - 50

- name: GeodeWindowsGfshDistributedTestOpenJDK11Metrics
  serial: true
  public: true
  plan:
  - get: geode-ci
  - get: once-a-day
    trigger: true
  - task: get_metrics
    config:
      inputs:
      - name: geode-ci
      outputs:
      - name: workspace
      platform: linux
      image_resource: *docker-geode-build-image
      run:
        path: /usr/bin/python3
        args:
        - geode-ci/ci/bin/concourse_job_performance.py
        - https://concourse.apachegeode-ci.info
        - develop
        - WindowsGfshDistributedTestOpenJDK11
        - 50

- name: GeodeWindowsIntegrationTestOpenJDK8Metrics
  serial: true
  public: true
  plan:
  - get: geode-ci
  - get: once-a-day
    trigger: true
  - task: get_metrics
    config:
      inputs:
      - name: geode-ci
      outputs:
      - name: workspace
      platform: linux
      image_resource: *docker-geode-build-image
      run:
        path: /usr/bin/python3
        args:
        - geode-ci/ci/bin/concourse_job_performance.py
        - https://concourse.apachegeode-ci.info
        - develop
        - WindowsIntegrationTestOpenJDK8
        - 50

- name: GeodeWindowsIntegrationTestOpenJDK11Metrics
  serial: true
  public: true
  plan:
  - get: geode-ci
  - get: once-a-day
    trigger: true
  - task: get_metrics
    config:
      inputs:
      - name: geode-ci
      outputs:
      - name: workspace
      platform: linux
      image_resource: *docker-geode-build-image
      run:
        path: /usr/bin/python3
        args:
        - geode-ci/ci/bin/concourse_job_performance.py
        - https://concourse.apachegeode-ci.info
        - develop
        - WindowsIntegrationTestOpenJDK11
        - 50

- name: GeodeWindowsUnitTestOpenJDK8Metrics
  serial: true
  public: true
  plan:
  - get: geode-ci
  - get: once-a-day
    trigger: true
  - task: get_metrics
    config:
      inputs:
      - name: geode-ci
      outputs:
      - name: workspace
      platform: linux
      image_resource: *docker-geode-build-image
      run:
        path: /usr/bin/python3
        args:
        - geode-ci/ci/bin/concourse_job_performance.py
        - https://concourse.apachegeode-ci.info
        - develop
        - WindowsUnitTestOpenJDK8
        - 50

- name: GeodeWindowsUnitTestOpenJDK11Metrics
  serial: true
  public: true
  plan:
  - get: geode-ci
  - get: once-a-day
    trigger: true
  - task: get_metrics
    config:
      inputs:
      - name: geode-ci
      outputs:
      - name: workspace
      platform: linux
      image_resource: *docker-geode-build-image
      run:
        path: /usr/bin/python3
        args:
        - geode-ci/ci/bin/concourse_job_performance.py
        - ((concourse-url))
        - develop
        - WindowsUnitTestOpenJDK11
        - 50

