/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.pivotal.jvsd;

/**
 *
 * @author jdeppe
 */
public class HUD extends javax.swing.JPanel {

	/**
	 * Creates new form HUD
	 */
	public HUD() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    xLabel = new javax.swing.JLabel();
    yLabel = new javax.swing.JLabel();

    setBackground(new java.awt.Color(134, 225, 194));
    setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
    setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
    setRequestFocusEnabled(false);

    jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getSize()-3f));
    jLabel1.setText("X:");

    jLabel2.setFont(jLabel2.getFont().deriveFont(jLabel2.getFont().getSize()-3f));
    jLabel2.setText("Y:");

    xLabel.setFont(xLabel.getFont().deriveFont(xLabel.getFont().getSize()-3f));
    xLabel.setText("0");

    yLabel.setFont(yLabel.getFont().deriveFont(yLabel.getFont().getSize()-3f));
    yLabel.setText("0");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(xLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel2)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(yLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        .addContainerGap(69, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(xLabel))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel2)
          .addComponent(yLabel))
        .addContainerGap(58, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents

  public void setXLabel(String label) {
    xLabel.setText(label);
  }

  public void setYLabel(String label) {
    yLabel.setText(label);
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel xLabel;
  private javax.swing.JLabel yLabel;
  // End of variables declaration//GEN-END:variables
}
