#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

{% from 'shared_jinja.yml' import pipeline_prefix with context %}
{% from 'shared_jinja.yml' import init_retry with context %}

groups:
- name: main
  jobs:
  - {{ build_test.name }}
{%- for test in tests %}
  {%- for java_test_version in (java_test_versions) if (java_test_version.name.endswith("jdk11") or (java_test_version.name.endswith("jdk8") and test.PLATFORM == "linux")) and ((not test.ONLY_JDK is defined) or test.ONLY_JDK == java_test_version.version) %}
  - {{test.name}}-test-{{java_test_version.name}}
  {%- endfor %}
{%- endfor %}
{%- for run_var in (benchmarks.flavors) %}
  - benchmark-{{ run_var.title }}
{%- endfor %}

resources:
- name: geode
  type: pull-request
  source:
    access_token: ((github-apachegeode-ci-read-only-token))
    repository: {{repository.fork}}/geode
    disable_ci_skip: false
    skip_ssl_verification: false
- name: geode-windows
  type: pull-request
  source:
    access_token: ((github-apachegeode-ci-read-only-token))
    repository: {{repository.fork}}/geode
    disable_ci_skip: false
    skip_ssl_verification: false
    labels: [windows]
- name: geode-jdk8
  type: pull-request
  source:
    access_token: ((github-apachegeode-ci-read-only-token))
    repository: {{repository.fork}}/geode
    disable_ci_skip: false
    skip_ssl_verification: false
    labels: [jdk8]
- name: geode-bench
  type: pull-request
  source:
    access_token: ((github-apachegeode-ci-read-only-token))
    repository: {{repository.fork}}/geode
    disable_ci_skip: false
    skip_ssl_verification: false
    labels: [benchmarks]
- name: geode-status
  type: pull-request
  source:
    access_token: ((github-pr-access-token))
    repository: {{repository.fork}}/geode
    disable_ci_skip: false
    skip_ssl_verification: false
- name: geode-ci
  type: git
  source:
    branch: {{repository.branch}}
    depth: 1
    paths:
    - ci/*
    uri: https://github.com/{{repository.upstream_fork}}/geode.git
- name: concourse-metadata-resource
  type: concourse-metadata-resource
  source: {}
- name: alpine-tools-image
  type: docker-image
  source:
    username: ((docker-username))
    password: ((docker-password))
    repository: gcr.io/((gcp-project))/((pipeline-prefix))alpine-tools
    tag: latest

- name: windows-builder-image-family
  type: gci
  source:
    key: ((concourse-gcp-key))
    family_project: ((gcp-project))
    family: ((pipeline-prefix))windows-geode-builder

- name: linux-builder-image-family
  type: gci
  source:
    key: ((concourse-gcp-key))
    family_project: ((gcp-project))
    family: ((pipeline-prefix))linux-geode-builder

- name: geode-benchmarks
  type: git
  source:
    branch: {{benchmarks.benchmark_branch}}
    depth: 1
    uri: https://github.com/((geode-fork))/geode-benchmarks.git

resource_types:
- name: gci
  type: registry-image
  source:
    registry_mirror:
      host: mirror.gcr.io
    repository: smgoller/gci-resource
- name: gcs-resource
  type: registry-image
  source:
    registry_mirror:
      host: mirror.gcr.io
    repository: frodenas/gcs-resource
- name: pull-request
  type: docker-image
  source:
    username: ((docker-username))
    password: ((docker-password))
    repository: gcr.io/((gcp-project))/((pipeline-prefix))github-pr-resource
    tag: latest
- name: concourse-metadata-resource
  type: docker-image
  source:
    password: ((docker-password))
    repository: gcr.io/((gcp-project))/((pipeline-prefix))concourse-metadata-resource
    tag: latest
    username: ((docker-username))
jobs:
- name: {{build_test.name}}
  public: true
  plan:
  - do:
    - in_parallel:
      - get: alpine-tools-image
      - get: geode
        trigger: true
        version: every
        attempts: 2
        params:
          integration_tool: rebase
      - get: geode-ci
        attempts: 2
      - get: {{ build_test.PLATFORM }}-builder-image-family
    - in_parallel:
      - do:
        - put: pull-request-job-pending
          resource: geode-status
          params:
            context: {{ build_test.name }}
            path: geode
            status: pending
          get_params: {skip_download: true}
      - do:
        - put: concourse-metadata-resource
        {{ init_retry()|indent(8) }}
        - task: create_instance
          image: alpine-tools-image
          config:
            platform: linux
            params:
              CPUS: {{build_test.CPUS}}
              RAM: {{build_test.RAM}}
              DISK: {{build_test.DISK}}
              GCP_PROJECT: ((gcp-project))
              GCP_NETWORK: ((gcp-network))
              GCP_SUBNETWORK: ((gcp-subnet))
              GCP_ZONE: ((gcp-zone))
              GEODE_BRANCH: {{repository.branch}}
              GEODE_FORK: {{repository.fork}}
              JAVA_BUILD_VERSION: {{ java_build_version.version }}
              JAVA_TEST_VERSION: {{ java_build_version.version }}
              IMAGE_FAMILY_NAME: ((pipeline-prefix))linux-geode-builder
            run:
              path: geode-ci/ci/scripts/create_instance.sh
            inputs:
            - name: concourse-metadata-resource
            - name: geode
            - name: geode-ci
            - name: attempts-log
              path: old
            - name: {{ build_test.PLATFORM}}-builder-image-family
              path: builder-image
            outputs:
            - name: instance-data
            - name: attempts-log
              path: new
          timeout: 20m
          attempts: 5
    - task: rsync_code_up
      image: alpine-tools-image
      config:
        platform: linux
        run:
          path: geode-ci/ci/scripts/rsync_code_up.sh
        inputs:
        - name: geode-ci
        - name: geode
        - name: instance-data
      timeout: 15m
      attempts: 5
    - task: build
      image: alpine-tools-image
      config:
        platform: linux
        params:
          JAVA_BUILD_VERSION: {{ java_build_version.version }}
          GRADLE_TASK: {{ build_test.GRADLE_TASK }}
          ARTIFACT_SLUG: {{build_test.ARTIFACT_SLUG}}
          JAVA_TEST_VERSION: {{ java_build_version.version }}
          CALL_STACK_TIMEOUT: {{build_test.CALL_STACK_TIMEOUT}}
          DUNIT_PARALLEL_FORKS: {{build_test.DUNIT_PARALLEL_FORKS}}
          GRADLE_TASK_OPTIONS: ""
          MAINTENANCE_VERSION: {{repository.branch}}
          PARALLEL_DUNIT: {{build_test.PARALLEL_DUNIT}}
          PARALLEL_GRADLE: {{build_test.PARALLEL_GRADLE}}
          ARTIFACT_BUCKET: ((artifact-bucket))
          SERVICE_ACCOUNT: ((concourse-gcp-account))
          GRADLE_GLOBAL_ARGS: ((gradle-global-args))
        run:
          path: geode-ci/ci/scripts/execute_build.sh
        inputs:
        - name: geode-ci
        - name: geode
        - name: instance-data
      timeout: {{build_test.EXECUTE_TEST_TIMEOUT}}
    on_failure:
      do:
      - put: pull-request-job-failure
        resource: geode-status
        params:
          context: {{ build_test.name }}
          path: geode
          status: failure
        get_params: {skip_download: true}
    ensure:
      do:
      - task: rsync_code_down
        image: alpine-tools-image
        config:
          platform: linux
          params:
            JAVA_BUILD_VERSION: {{ java_build_version.version }}
            ARTIFACT_SLUG: {{build_test.ARTIFACT_SLUG}}
          run:
            path: geode-ci/ci/scripts/rsync_code_down.sh
          inputs:
          - name: geode
          - name: geode-ci
          - name: instance-data
          outputs:
          - name: geode-results
        timeout: 15m
        attempts: 5
      ensure:
        in_parallel:
        - task: archive_results
          image: alpine-tools-image
          config:
            platform: linux
            params:
              ARTIFACT_SLUG: {{build_test.ARTIFACT_SLUG}}
              GRADLE_TASK: {{build_test.GRADLE_TASK}}
              MAINTENANCE_VERSION: {{repository.branch}}
              ARTIFACT_BUCKET: ((artifact-bucket))
              SERVICE_ACCOUNT: ((concourse-gcp-account))
            run:
              path: geode-ci/ci/scripts/archive_results.sh
            inputs:
            - name: concourse-metadata-resource
            - name: geode
            - name: geode-ci
            - name: geode-results
        - task: delete_instance
          image: alpine-tools-image
          config:
            platform: linux
            run:
              path: geode-ci/ci/scripts/delete_instance.sh
            inputs:
            - name: geode
            - name: geode-ci
            - name: instance-data
          timeout: 1h
    on_success:
      do:
      - put: pull-request-job-success
        resource: geode-status
        params:
          context: {{ build_test.name }}
          path: geode
          status: success
        get_params: {skip_download: true}


{% for test in tests %}
  {%- for java_test_version in (java_test_versions) if (java_test_version.name.endswith("jdk11") or (java_test_version.name.endswith("jdk8") and test.PLATFORM == "linux")) and ((not test.ONLY_JDK is defined) or test.ONLY_JDK == java_test_version.version) %}
- name: {{test.name}}-test-{{java_test_version.name}}
  public: true
  plan:
  - do:
    - in_parallel:
      - get: alpine-tools-image
{%- if test.PLATFORM == "linux" and (java_test_version.name.endswith("jdk11") or test.name == "unit" or test.name == "stress-new" or test.name == "distributed") %}
      - get: geode
{%- elif test.PLATFORM == "linux" %}
      - get: geode
        resource: geode-jdk8
{%- else %}
      - get: geode
        resource: geode-windows
{%- endif %}
        trigger: true
        version: every
        attempts: 2
        params:
          integration_tool: rebase
      - get: geode-ci
        attempts: 2
      - get: {{ test.PLATFORM }}-builder-image-family
    - in_parallel:
      - do:
        - put: pull-request-job-pending
          resource: geode-status
          params:
            context: {{test.name}}-test-{{java_test_version.name}}
            path: geode
            status: pending
          get_params: {skip_download: true}
      - do:
        - put: concourse-metadata-resource
        {{ init_retry()|indent(8) }}
        - task: create_instance-{{java_test_version.name}}
          image: alpine-tools-image
          config:
            platform: linux
            params:
              CPUS: {{test.CPUS}}
              DISK: {{test.DISK}}
              GEODE_BRANCH: {{repository.branch}}
              GEODE_FORK: {{repository.fork}}
              GCP_PROJECT: ((gcp-project))
              GCP_NETWORK: ((gcp-network))
              GCP_SUBNETWORK: ((gcp-subnet))
              GCP_ZONE: ((gcp-zone))
              RAM: {{test.RAM}}
              JAVA_BUILD_VERSION: {{ java_build_version.version }}
              JAVA_TEST_VERSION: {{ java_test_version.version }}
              IMAGE_FAMILY_NAME: ((pipeline-prefix)){{ test.PLATFORM }}-geode-builder
            run:
              path: geode-ci/ci/scripts/create_instance.sh
            inputs:
            - name: concourse-metadata-resource
            - name: geode
            - name: geode-ci
            - name: attempts-log
              path: old
            - name: {{ test.PLATFORM}}-builder-image-family
              path: builder-image
            outputs:
            - name: instance-data
            - name: attempts-log
              path: new
          timeout: 20m
          attempts: 5
    - task: rsync_code_up-{{java_test_version.name}}
      image: alpine-tools-image
      config:
        platform: linux
        run:
          path: geode-ci/ci/scripts/rsync_code_up.sh
        inputs:
        - name: geode
        - name: geode-ci
        - name: instance-data
      timeout: 15m
      attempts: 5
    - task: execute_tests-{{java_test_version.name}}
      image: alpine-tools-image
      config:
        platform: linux
        params:
          ARTIFACT_SLUG: {{test.ARTIFACT_SLUG}}
          JAVA_BUILD_VERSION: {{ java_build_version.version }}
          JAVA_TEST_VERSION: {{ java_test_version.version }}
        {%- if test.CALL_STACK_TIMEOUT %}
          CALL_STACK_TIMEOUT: {{test.CALL_STACK_TIMEOUT}}
        {%- endif %}
          DUNIT_PARALLEL_FORKS: {{test.DUNIT_PARALLEL_FORKS}}
          GRADLE_TASK: {{test.GRADLE_TASK}}
        {%- if test.GRADLE_TASK_OPTIONS %}
          GRADLE_TASK_OPTIONS: {{test.GRADLE_TASK_OPTIONS}}
        {%- else %}
          GRADLE_TASK_OPTIONS: ""
        {%- endif %}
          MAINTENANCE_VERSION: {{repository.branch}}
          PARALLEL_DUNIT: {{test.PARALLEL_DUNIT}}
        {% if test.PARALLEL_GRADLE is defined %}
          PARALLEL_GRADLE: {{test.PARALLEL_GRADLE}}
        {% else %}
          PARALLEL_GRADLE: true
        {% endif %}
          ARTIFACT_BUCKET: ((artifact-bucket))
          SERVICE_ACCOUNT: ((concourse-gcp-account))
          GRADLE_GLOBAL_ARGS: ((gradle-global-args))
        run:
          {%- if test.name=="stress-new" %}
          path: geode-ci/ci/scripts/repeat-new-tests.sh
          {%- else %}
          path: geode-ci/ci/scripts/execute_tests.sh
          {%- endif %}
        inputs:
        - name: geode
        - name: geode-ci
        - name: instance-data
      timeout: {{test.EXECUTE_TEST_TIMEOUT}}
    on_failure:
      do:
      - put: pull-request-job-failure
        resource: geode-status
        params:
          context: {{test.name}}-test-{{java_test_version.name}}
          path: geode
          status: failure
        get_params: {skip_download: true}
    ensure:
      do:
      - task: rsync_code_down-{{java_test_version.name}}
        image: alpine-tools-image
        config:
          platform: linux
          params:
            JAVA_BUILD_VERSION: {{ java_build_version.version }}
            ARTIFACT_SLUG: {{test.ARTIFACT_SLUG}}
          run:
            path: geode-ci/ci/scripts/rsync_code_down.sh
          inputs:
          - name: geode
          - name: geode-ci
          - name: instance-data
          outputs:
          - name: geode-results
        timeout: 15m
        attempts: 5
      ensure:
        in_parallel:
        - task: archive-results-{{java_test_version.name}}
          image: alpine-tools-image
          config:
            platform: linux
            params:
              ARTIFACT_SLUG: {{test.ARTIFACT_SLUG}}
              GRADLE_TASK: {{test.GRADLE_TASK}}
              MAINTENANCE_VERSION: {{repository.branch}}
              ARTIFACT_BUCKET: ((artifact-bucket))
              SERVICE_ACCOUNT: ((concourse-gcp-account))
            run:
              path: geode-ci/ci/scripts/archive_results.sh
            inputs:
            - name: concourse-metadata-resource
            - name: geode
            - name: geode-ci
            - name: geode-results
        - task: delete_instance-{{java_test_version.name}}
          image: alpine-tools-image
          config:
            platform: linux
            run:
              path: geode-ci/ci/scripts/delete_instance.sh
            inputs:
            - name: geode
            - name: geode-ci
            - name: instance-data
          timeout: 1h
    on_success:
      do:
      - put: pull-request-job-success
        resource: geode-status
        params:
          context: {{test.name}}-test-{{java_test_version.name}}
          path: geode
          status: success
        get_params: {skip_download: true}
{% endfor %}
{% endfor %}

{% for run_var in (benchmarks.flavors) %}
- name: benchmark-{{ run_var.title }}
  public: true
  max_in_flight: {{ run_var.max_in_flight }}
  plan:
  - in_parallel:
    - get: geode-ci
      attempts: 2
    - get: alpine-tools-image
      attempts: 2
    - get: geode
      resource: geode-bench
      trigger: true
      version: every
      attempts: 2
      params:
        integration_tool: rebase
    - get: geode-benchmarks
    - put: concourse-metadata-resource
  - do:
    - put: pull-request-job-pending
      resource: geode-status
      params:
        context: benchmark-{{ run_var.title }}
        path: geode
        status: pending
      get_params: {skip_download: true}
  - do:
    - task: run-benchmarks-{{ run_var.title }}
      image: alpine-tools-image
      config:
        platform: linux
        params:
          AWS_ACCESS_KEY_ID: ((benchmarks-access-key-id))
          AWS_SECRET_ACCESS_KEY: ((benchmarks-secret-access-key))
          AWS_DEFAULT_REGION: us-west-2
          AWS_REGION: us-west-2
          ARTIFACT_BUCKET: ((artifact-bucket))
          BENCHMARKS_BRANCH: {{benchmarks.benchmark_branch}}
          BASELINE_BRANCH: {{run_var.baseline_branch if run_var.baseline_branch is defined else benchmarks.baseline_branch_default}}
          BASELINE_VERSION: {{run_var.baseline_version if run_var.baseline_version is defined else benchmarks.baseline_version_default}}
          FLAGS: {{ run_var.flag }}
          TAG_POSTFIX: -{{ run_var.title }}
          TEST_OPTIONS: {{ run_var.options }}
          PURPOSE: ((pipeline-prefix))geode-benchmarks
        run:
          path: geode-ci/ci/scripts/run_benchmarks.sh
        inputs:
        - name: geode
        - name: geode-ci
        - name: geode-benchmarks
        - name: concourse-metadata-resource
        outputs:
        - name: results
      timeout: {{ run_var.timeout }}
      on_failure:
        do:
        - put: pull-request-job-failure
          resource: geode-status
          params:
            context: benchmark-{{ run_var.title }}
            path: geode
            status: failure
          get_params: {skip_download: true}
      ensure:
        do:
        - task: cleanup_benchmarks
          image: alpine-tools-image
          config:
            platform: linux
            params:
              AWS_ACCESS_KEY_ID: ((benchmarks-access-key-id))
              AWS_SECRET_ACCESS_KEY: ((benchmarks-secret-access-key))
              AWS_DEFAULT_REGION: us-west-2
              AWS_REGION: us-west-2
              ARTIFACT_BUCKET: ((artifact-bucket))
              BASELINE_BRANCH: {{run_var.baseline_branch if run_var.baseline_branch is defined else benchmarks.baseline_branch_default}}
              BASELINE_VERSION: {{run_var.baseline_version if run_var.baseline_version is defined else benchmarks.baseline_version_default}}
              FLAGS: {{ run_var.flag }}
              TAG_POSTFIX: -{{ run_var.title }}
              TEST_OPTIONS: {{ run_var.options }}
            run:
              path: geode-ci/ci/scripts/cleanup_benchmarks.sh
            inputs:
            - name: geode
            - name: geode-ci
            - name: geode-benchmarks
            - name: concourse-metadata-resource
            - name: results
      on_success:
        do:
        - put: pull-request-job-success
          resource: geode-status
          params:
            context: benchmark-{{ run_var.title }}
            path: geode
            status: success
          get_params: {skip_download: true}
{% endfor %}
