# This is invoked from ANT with many 
# variables defined on the command line.

default: all

LIBRARY = userobject
CPP_OPTIONS =

XTRA_LIB_PATHS =
XTRA_LIBS =
XTRA_INCS =

include $(BASEDIR)/makefiles/test_library.gmk
